### ISSUE TITLE
Ensure images have a specific release tag

### ISSUE THREAD

**Issue by mpackard** [tapis-project/tapis-deployer#101]
e.g. no "minio/mnio" or "postgres:latest" or "abaco/prom:dev"

**Comment by joestubbs** [comment]
Files/Images that still need to be updated:
tapis-kube-1.3/actors/api/grafana.yml:        image: grafana/grafana
tapis-kube-1.3/actors/api/mongo-pvc.yml:        image: alpine:latest
tapis-kube-1.3/actors/api/nfs-pvc.yml:        image: alpine:latest
tapis-kube-1.3/actors/api/rabbitmq-pvc.yml:        image: alpine:latest

tapis-kube-1.3/authenticator/ldap/deploy.yml:        image: tacc/slapd

tapis-kube-1.3/meta/backup/pbm/pbm.yml:          image: tapis/mongodb-backup:latest
tapis-kube-1.3/meta/mongo/pvc.yml:        image: alpine:latest

tapis-kube-1.3/monitoring/apps/tapis-exporter.yml:        image: tapis/exporter:latest

tapis-kube-1.3/pods/postgres-pvc.yml:        image: alpine:latest
tapis-kube-1.3/pods/traefik-proxy.yml:        image: notchristiangarcia/traefik-testing:latest

tapis-kube-1.3/streams/mysql/pvc.yml:#        image: alpine:latest
