### ISSUE TITLE
Tapis 1.6 Release

### ISSUE THREAD

**Issue by mpackard** [tapis-project/tapis-deployer#342]

**Comment by richcar58** [comment]
**Java Services 1.6.0 Changelog Information**

Systems: 1.5.10 to 1.6.0 (tapis/systems)
Systems changes: https://github.com/tapis-project/tapis-systems/blob/dev/CHANGELOG.md

Apps: 1.5.10 to 1.6.0 (tapis/apps)
Apps changes: https://github.com/tapis-project/tapis-apps/blob/dev/CHANGELOG.md

Notifications: 1.5.12 to 1.6.0 (tapis/notifications, notifications-dispatcher)
Notification changes: https://github.com/tapis-project/tapis-notifications/blob/dev/CHANGELOG.md

Files: 1.5.10 to 1.6.0 (tapis/tapis-files, tapis/tapis-files-workers)
Files changes: https://github.com/tapis-project/tapis-files/blob/dev/CHANGELOG.md

Jobs: 1.5.10 to 1.6.0 (tapis/jobsworker, jobsmigrate, jobsapi)
Jobs changes: https://github.com/tapis-project/tapis-jobs/blob/dev/tapis-jobsapi/CHANGELOG.md

Security: 1.5.10 to 1.6.0 (tapis/securitymigrate, securityadmin, securityapi, securityexport)
Security changes: https://github.com/tapis-project/tapis-security/blob/dev/tapis-securityapi/CHANGELOG.md

Meta: 1.5.10 to 1.6.0 (tapis/metaapi, tapis-meta-rh-server)
Meta changes: [https://github.com/tapis-project/tapis-meta/blob/dev/CHANGELOG.m](https://github.com/tapis-project/tapis-meta/blob/dev/CHANGELOG.md)
