### ISSUE TITLE
reduce diagnostics errors to 0

### ISSUE THREAD

**Issue by joestubbs** [tapis-project/tapis-deployer#46]
This is an "epic" style issue to reduce the number of errors reported by the deployer diagnostics utility (`-d` flag) down to 0. Currently, the diagnostics utility reports 56 error:

`Errors within loadable templates (see messages above): 56`

Additionally, 14 warnings are reported:
`Warnings within loadable templates (see messages above): 14`

These will be tackled in another issue.

**Comment by joestubbs** [comment]
with the latest updates, we are now down to 16 errors and 11 warnings.

**Comment by joestubbs** [comment]
hey @kevinpricethesecond / @mpackard this is done, right? can we close it?

**Comment by joestubbs** [comment]
I see on the project board the status is "done" so I am closing. Feel free to open back up.

**Comment by kevinpricethesecond** [comment]
Yes, that was done. Thanks for cleaning up.
