### ISSUE TITLE
Create python tapis check script that confirms 1 or more dependent component is up

### ISSUE THREAD

**Issue by mpackard** [tapis-project/tapis-deployer#75]
- python script
- can be run from command line by tapis user
- also built into docker container so it can be used in kube jobs/pods/deployments
- takes arguments to say which components to check
- 2 areas to start: 
  - check that vault is up and unsealed
  - check that component X healthcheck is good 
- You can refer to the admin/verification scripts to help with getting started (see tapis-deployer/templates/admin/verification)

**Comment by joestubbs** [comment]
There is a standalone python script in a gitlab repo but it is not been integrated into deployer.
